config/routes.rb
Rails.application.routes.draw do

  root 'high_voltage/pages#show', id: 'home'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :users do
    get  'select_repos'    => 'on_boarding#select_repos'
    post 'start_playing'   => 'on_boarding#start_playing'
  end

  namespace :webhooks do
    post 'github/receive'
  end

  scope ':username' do
    get '/' => 'users/profile#show', as: :profile
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable,
          :trackable, :validatable, :omniauthable,
          :omniauth_providers => [:github]

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.email          = auth.info.email
      user.password       = Devise.friendly_token[0,20]
      user.screen_name    = auth.info.nickname
      user.username       = auth.info.nickname.parameterize
      user.image          = auth.info.image
      user.github_token   = auth.credentials.token
      user.github_user_id = auth.uid
    end
  end

  def configure_octokit
    Octokit.configure do |config|
      config.access_token = self.github_token
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => 'github') if is_navigational_format?
      @user.configure_octokit
    else
      session['devise.github_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/on_boarding_controller.rb
class Users::OnBoardingController < ApplicationController
  def select_repos
    @repositories = Octokit.repositories
  end

  def start_playing
    @selected_repositories = params[:repositories]
    @selected_repositories.keys.each do |repository_name|
      create_webhook(repository_name)
    end
  end

  private

  def create_webhook(repository_name)
    webhook_url = "#{root_url}/webhook/github/"
    Octokit.create_hook(repository_name, 'web',
      {
        :url => webhook_url,
        :content_type => 'json'
      },
      {
        :events => ['*'],
        :active => true
      }
    )
  end
end

app/controllers/users/profile_controller.rb
class Users::ProfileController < ApplicationController
  before_action :retrieve_user
  def show
  end

  private

  def retrieve_user
    @user = User.find_by_username(params[:username].parameterize)
  end
end

app/controllers/webhooks/github_controller.rb
class Webhooks::GithubController < ApplicationController
  skip_before_filter :verify_authenticity_token
  def receive
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users/on_boarding_helper.rb
module Users::OnBoardingHelper
end

app/helpers/users/profile_helper.rb
module Users::ProfileHelper
end

app/helpers/webhooks/github_helper.rb
module Webhooks::GithubHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? "GitGame | #{yield(:title)}" : "GitGame" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: 'partials/topbar' %>
    <%= render partial: 'partials/alert_center' %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home">
  <div class="header">
    <div class="row">
      <div class="small-8 columns end">
        <h1>Work & play at the same time.</h1>
        <p>
          Increase your productivity and challenge your coworkers, while helping
          open-source community.
        </p>
      </div>
    </div>
    <div class="row">
      <div class="small-8 columns">
        <%= link_to (fa_icon '2x github', text: "Sign in with Github"), user_omniauth_authorize_path(:github), class: "expand radius github button" %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_alert_center.html.erb
<div class="row">
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>
</div>

app/views/partials/_topbar.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to('GitGame', root_url) %></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <% if user_signed_in? %>
    <ul class="right">
      <li class="has-dropdown">
        <%= link_to(current_user.screen_name, profile_path(username: current_user.username)) %>
        <ul class="dropdown">
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        </ul>
      </li>
    </ul>
    <% else %>
    <ul class="right">
      <li class="active"><%= link_to "Sign in with Github", user_omniauth_authorize_path(:github) %></li>
    </ul>
    <% end %>
  </section>
</nav>

app/views/users/on_boarding/generate_token.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2 class="text-center">There is your unique token.</h2>
    <p class="text-center"><%= @token %></p>
  </div>
</div>
<div class="row">
  <div class="small-8 small-push-2 columns">
    <%= link_to 'Continue', users_select_repos_path, class: 'expand large success button' %>
  </div>
</div>

app/views/users/on_boarding/select_repos.html.erb
<%= form_tag(controller: "on_boarding", action: "start_playing") do %>
  <% @repositories.each do |repository| %>
  <div class="row">
    <div class="small-1 columns">
      <div class="switch">
        <%= check_box_tag("repositories[#{repository.full_name}]", 'selected', checked: true) %>
        <%= label_tag("repositories[#{repository.full_name}]") %>
      </div>
    </div>
    <div class="small-3 columns">
      <%= link_to(repository.full_name, repository.html_url, class:"expand tiny button github") %>
    </div>
    <div class="small-8 columns">
      <%= repository.description %>
    </div>
  </div>
  <% end %>
  <div class="row">
    <div class="small-8 small-push-2 columns">
      <%= button_to 'Create a webhook for each of these repositories.', users_start_playing_path, class: 'expand large success button' %>
    </div>
  </div>
<% end %>

app/views/users/on_boarding/start_playing.html.erb
<h1>Users::OnBoarding#start_playing</h1>
<p>Find me in app/views/users/on_boarding/start_playing.html.erb</p>

app/views/users/profile/show.html.erb
<div class="header">
  <div class="row">
    <div class="small-4 columns">
      <%= image_tag @user.image %>
      <h1 class="text-center"><%= @user.screen_name %></h1>
    </div>
    <div class="small-8 columns">
    </div>
  </div>
</div>
<div class="languages-bar">
  <div class="row">
    <div class="small-12 columns"></div>
  </div>
</div>

app/views/webhooks/github/receive.html.erb
<h1>Webhooks::Github#receive</h1>
<p>Find me in app/views/webhooks/github/receive.html.erb</p>